Enhanced the capabilities of FrenchRepublicanCalendarCore
Snowy1803/FrenchRepublicanCalendarCore pull request #1
Opened 2022-08-03 11:48 UTC by AaronAdelman

In incorporating FrenchRepublicanCalendarCore into one of my projects, I realized that it did not support time zones, so I fixed it.  I also made it possible to treat Sansculottides as a 13th month in formatted dates, and I was very careful to make sure that the original API was still valid.  Enjoy.

2022-08-03 17:16 UTC, Snowy1803 requested changes
I put each comment once, but the naming convention issue and the duplicate initialisers/functions is the same everywhere
Otherwise it looks like a useful feature! Thanks for contributing :)

2022-08-03 17:16 UTC, Snowy1803 commented on Sources/FrenchRepublicanCalendarCore/DecimalTime.swift
> +    init(base: Date = Date(), timeZone: TimeZone?) {
you could just put a default argument value of nil for timeZone instead of creating another initialiser

2022-08-03 17:16 UTC, Snowy1803 commented on Sources/FrenchRepublicanCalendarCore/DecimalTime.swift
> +        var GregorianCalendar: Calendar = Calendar.gregorian
Use the [Swift naming conventions](https://www.swift.org/documentation/api-design-guidelines/#general-conventions): lowerCamelCase for variables

2022-08-03 17:16 UTC, Snowy1803 commented on Sources/FrenchRepublicanCalendarCore/FrenchRepublicanDate+Formatting.swift
> +            "Belle de nuit": "Mirabilis_jalapa", "Amaryllis": "Amaryllis_(plante)", "Erable sucré": "%C3%89rable_%C3%A0_sucre", "Perce Neige": "Perce-neige", "Laurier thym": "Viorne_tin", "Thimèle":
avoid reformatting code, it's more readable line per line

2022-08-04 14:11 UTC, AaronAdelman commented
Requested changes have been made.  Have run the unit tests just to make sure everything still works.

2022-08-04 15:38 UTC, Snowy1803 commented on Sources/FrenchRepublicanCalendarCore/FrenchRepublicanDateOptions.swift
> +    public init(romanYear: Bool, variant: Variant, treatSansculottidesAsAMonth: Bool) {
Could use a default value of false for treatSansculottidesAsAMonth instead of duplicating here too

2022-08-04 15:41 UTC, Snowy1803 commented
It could also be useful to add unit tests for your additions; it's not necessary for treatSansculottidesAsAMonth, it's pretty straightforward, but the time zone support could be tested

2022-08-04 15:43 UTC, AaronAdelman commented
Thanks.  I forgot about that one.

Aaron Adelman

> ‫ב-4 באוג׳ 2022, בשעה 18:38, ‏‏⁨Emil Pedersen⁩ ***@***.***⁩> כתב/ה:‬
> 
> 
> @Snowy1803 commented on this pull request.
> 
> In ‏⁨Sources/FrenchRepublicanCalendarCore/FrenchRepublicanDateOptions.swift⁩ ‏<⁨https://github.com/Snowy1803/FrenchRepublicanCalendarCore/pull/1#discussion_r937946373⁩>:
> 
> >      public init(romanYear: Bool, variant: Variant) {
> +        self.init(romanYear: romanYear, variant: variant, treatSansculottidesAsAMonth: false)
> +    }
> +    
> +    public init(romanYear: Bool, variant: Variant, treatSansculottidesAsAMonth: Bool) {
> Could use a default value of false for treatSansculottidesAsAMonth instead of duplicating here too
> 
> —
> Reply to this email directly, ‏⁨view it on GitHub⁩ ‏<⁨https://github.com/Snowy1803/FrenchRepublicanCalendarCore/pull/1#pullrequestreview-1062161877⁩>, or ‏⁨unsubscribe⁩ ‏<⁨https://github.com/notifications/unsubscribe-auth/AHCTW3FPA6OJK5JIHBKFDXLVXPPXRANCNFSM55ORMWIQ⁩>.
> You are receiving this because you authored the thread.
>

2022-08-04 15:44 UTC, AaronAdelman commented
Will see what I can do about that.  

Aaron Adelman

> ‫ב-4 באוג׳ 2022, בשעה 18:41, ‏‏⁨Emil Pedersen⁩ ***@***.***⁩> כתב/ה:‬
> 
> 
> It could also be useful to add unit tests for your additions; it's not necessary for treatSansculottidesAsAMonth, it's pretty straightforward, but the time zone support could be tested
> 
> —
> Reply to this email directly, ‏⁨view it on GitHub⁩ ‏<⁨https://github.com/Snowy1803/FrenchRepublicanCalendarCore/pull/1#issuecomment-1205428007⁩>, or ‏⁨unsubscribe⁩ ‏<⁨https://github.com/notifications/unsubscribe-auth/AHCTW3ENFREM3QGZV52LXI3VXPQCRANCNFSM55ORMWIQ⁩>.
> You are receiving this because you authored the thread.
>

2022-08-04 19:53 UTC, AaronAdelman commented
Good call asking for time zone support unit tests.  I’m getting some odd results for Anchorage and Honolulu.  Looks like there’s some serious debugging to do to figure out what went wrong.

Aaron Adelman 


> ‫ב-4 באוג׳ 2022, בשעה 18:44, ‏‏⁨ד״ר אַהֲרֹן שְׁלֹמֹה אֵדֶלְמָן PhD⁩ ***@***.***⁩> כתב/ה:‬
> 
> Will see what I can do about that.  
> 
> Aaron Adelman
> 
>> ‫ב-4 באוג׳ 2022, בשעה 18:41, ‏‏⁨Emil Pedersen⁩ ***@***.***⁩ ***@***.***⁩>⁩> כתב/ה:‬
>> 
>> 
>> It could also be useful to add unit tests for your additions; it's not necessary for treatSansculottidesAsAMonth, it's pretty straightforward, but the time zone support could be tested
>> 
>> —
>> Reply to this email directly, ‏⁨view it on GitHub⁩ ‏<⁨https://github.com/Snowy1803/FrenchRepublicanCalendarCore/pull/1#issuecomment-1205428007⁩>, or ‏⁨unsubscribe⁩ ‏<⁨https://github.com/notifications/unsubscribe-auth/AHCTW3ENFREM3QGZV52LXI3VXPQCRANCNFSM55ORMWIQ⁩>.
>> You are receiving this because you authored the thread.
>> 
>

2022-08-11 15:57 UTC, AaronAdelman commented
Sorry for this taking so long, but other things happening over here have made it not optimal for debugging.  After a lot making it very explicit what is being tested, the tests finally all pass.  This includes testing in the user’s time zone, 10 different time zones from across the planet, testing for 1970-01-01, and testing for 2022-08-08 (the date that particular subtest was written).  

Enjoy.

Aaron Adelman

ד״ר אַהֲרֹן שְׁלֹמֹה אֵדֶלְמָן • Aaron Solomon Adelman, PhD
מתכנת • Programmer
***@***.***
http://www.linkedin.com/in/aaronsolomonadelman

> ‫ב-4 באוג׳ 2022, בשעה 22:53, ‏‏⁨ד״ר אַהֲרֹן שְׁלֹמֹה אֵדֶלְמָן PhD⁩ ***@***.***⁩> כתב/ה:‬
> 
> Good call asking for time zone support unit tests.  I’m getting some odd results for Anchorage and Honolulu.  Looks like there’s some serious debugging to do to figure out what went wrong.
> 
> Aaron Adelman 
> 
> 
>> ‫ב-4 באוג׳ 2022, בשעה 18:44, ‏‏⁨ד״ר אַהֲרֹן שְׁלֹמֹה אֵדֶלְמָן PhD⁩ ***@***.***⁩ ***@***.***⁩>⁩> כתב/ה:‬
>> 
>> Will see what I can do about that.  
>> 
>> Aaron Adelman
>> 
>>> ‫ב-4 באוג׳ 2022, בשעה 18:41, ‏‏⁨Emil Pedersen⁩ ***@***.***⁩ ***@***.***⁩>⁩> כתב/ה:‬
>>> 
>>> 
>>> It could also be useful to add unit tests for your additions; it's not necessary for treatSansculottidesAsAMonth, it's pretty straightforward, but the time zone support could be tested
>>> 
>>> —
>>> Reply to this email directly, ‏⁨view it on GitHub⁩ ‏<⁨https://github.com/Snowy1803/FrenchRepublicanCalendarCore/pull/1#issuecomment-1205428007⁩>, or ‏⁨unsubscribe⁩ ‏<⁨https://github.com/notifications/unsubscribe-auth/AHCTW3ENFREM3QGZV52LXI3VXPQCRANCNFSM55ORMWIQ⁩>.
>>> You are receiving this because you authored the thread.
>>> 
>> 
>

2025-11-02 02:00 UTC, closed without merging